"use client";

import Link from "next/link";
import { Activity, AlertTriangle, ArrowRight, BookCheck, CalendarClock, CalendarDays, CheckCircle2, ClipboardCheck, Clock3, GraduationCap, HeartHandshake, ListTodo, MessageSquareText, School, Sparkles, TrendingUp, UserCheck, UsersRound } from "lucide-react";
import { activities, assessments, classes, notifications, profiles, students, subjects } from "@/lib/mock-data";
import type { Role, Tone } from "@/lib/types";
import { Avatar, Button, Insight, PageHeader, ProgressBar, SectionHeader, StatCard, StatusBadge } from "./ui";
import { DistributionChart, PerformanceChart, SchoolTrendChart, SubjectChart } from "./charts";

export function Dashboard({ role }: { role: Role }) {
  if (role === "student") return <StudentDashboard />;
  if (role === "parent") return <ParentDashboard />;
  if (role === "teacher") return <TeacherDashboard />;
  if (role === "coordinator") return <CoordinatorDashboard />;
  return <DirectorDashboard />;
}

function Welcome({ role, title, text, children }: { role: Role; title: string; text: string; children?: React.ReactNode }) {
  return <div className="mb-6 flex flex-col gap-4 rounded-lg border border-blue-100 bg-[#eef5ff] p-5 md:flex-row md:items-center md:justify-between md:p-6"><div className="flex items-center gap-4"><Avatar index={profiles[role].avatar} size="lg" /><div><p className="text-lg font-bold text-slate-900 md:text-xl">{title}</p><p className="mt-1 text-xs leading-5 text-slate-600 md:text-sm">{text}</p></div></div>{children}</div>;
}

function StudentDashboard() {
  return <div className="page-enter"><Welcome role="student" title="Olá, Lucas 👋" text="Seu desempenho está evoluindo. Veja o que merece sua atenção hoje."><div className="grid grid-cols-2 gap-x-6 gap-y-2 text-xs"><div><span className="text-slate-500">Turma</span><strong className="ml-2">8º A</strong></div><div><span className="text-slate-500">Turno</span><strong className="ml-2">Manhã</strong></div><div><span className="text-slate-500">Série</span><strong className="ml-2">8º ano</strong></div><div><span className="text-slate-500">Matrícula</span><strong className="ml-2">20261031</strong></div></div></Welcome>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Média geral" value="8,4" detail="Meta anual: 7,0" icon={TrendingUp} tone="success" trend="+0,5" /><StatCard label="Frequência" value="94%" detail="423 de 450 aulas" icon={UserCheck} tone="success" /><StatCard label="Faltas" value="7" detail="2 justificadas" icon={CalendarDays} tone="warning" /><StatCard label="Próximas avaliações" value="3" detail="Nos próximos 10 dias" icon={ClipboardCheck} tone="info" /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.85fr]"><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Meu desempenho" description="Evolução da média nos bimestres" action={<StatusBadge tone="success">Em evolução</StatusBadge>} /><PerformanceChart /></section><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Desempenho por disciplina" description="Médias do 3º bimestre" /><SubjectChart /></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.85fr]"><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Próximas avaliações" action={<Link href="/aluno/avaliacoes" className="text-xs font-semibold text-blue-700">Ver todas</Link>} /><div className="grid gap-3 md:grid-cols-3">{assessments.map((item) => <div key={item.subject} className="rounded-lg border border-slate-200 p-4"><div className="flex items-start justify-between"><div><p className="text-xs font-bold text-slate-900">{item.subject}</p><p className="mt-1 text-[11px] text-slate-500">{item.title}</p></div><span className="rounded-md bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">{item.date}</span></div><p className="mt-4 text-[11px] text-slate-600">{item.content}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-slate-400"><Clock3 className="h-3 w-3" />{item.time}</p></div>)}</div></section><section className="space-y-3"><Insight tone="success" icon={Sparkles} title="Boa evolução" text="Você melhorou 12% em Matemática neste bimestre." /><Insight tone="warning" icon={ListTodo} title="Organize sua semana" text="2 atividades precisam ser entregues até sexta-feira." /></section></div>
  </div>;
}

function ParentDashboard() {
  return <div className="page-enter"><PageHeader eyebrow="Painel da família" title="Olá, Mariana." description="Acompanhe a vida escolar de Lucas de forma simples e próxima." action={<label className="flex items-center gap-2 text-xs text-slate-500"><span>Visualizando</span><select className="h-9 rounded-md border border-slate-200 bg-white px-3 font-semibold text-slate-700"><option>Lucas Silva · 8º A</option><option>Ana Silva · 6º B</option></select></label>} /><div className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6"><StatCard label="Média geral" value="8,4" detail="Acima da meta" icon={TrendingUp} tone="success" /><StatCard label="Frequência" value="94%" detail="Situação adequada" icon={UserCheck} tone="success" /><StatCard label="Faltas" value="7" detail="2 justificadas" icon={CalendarDays} tone="warning" /><StatCard label="Registros" value="1" detail="Orientação concluída" icon={HeartHandshake} tone="neutral" /><StatCard label="Pendências" value="2" detail="Atividades abertas" icon={ListTodo} tone="warning" /><StatCard label="Avaliações" value="3" detail="Próximos 10 dias" icon={ClipboardCheck} tone="info" /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.85fr]"><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Evolução acadêmica" description="Média de Lucas ao longo do ano" /><PerformanceChart /></section><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Desempenho por disciplina" /><SubjectChart /></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Resumo do Lucas" description="Panorama do 3º bimestre" /><div className="grid gap-4 sm:grid-cols-2">{subjects.slice(0, 4).map((subject) => <div key={subject.name} className="rounded-md border border-slate-100 p-3"><div className="mb-2 flex justify-between text-xs"><span className="font-semibold">{subject.name}</span><strong>{subject.score.toFixed(1).replace(".", ",")}</strong></div><ProgressBar value={subject.score * 10} tone={subject.score >= 8 ? "success" : "warning"} /></div>)}</div></section><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Central de alertas" action={<Link href="/responsavel/alertas" className="text-xs font-semibold text-blue-700">Abrir central</Link>} /><div className="space-y-4">{notifications.map((n, i) => <div key={n.title} className="flex gap-3"><div className="relative"><span className="block h-2.5 w-2.5 rounded-full bg-blue-600" />{i < notifications.length - 1 && <span className="absolute left-[4px] top-3 h-10 w-px bg-slate-200" />}</div><div><p className="text-xs font-semibold">{n.title}</p><p className="mt-1 text-[11px] text-slate-500">{n.detail} · {n.time}</p></div></div>)}</div></section></div>
  </div>;
}

function TeacherDashboard() {
  return <div className="page-enter"><Welcome role="teacher" title="Olá, Prof. Rafael." text="Você tem 4 aulas e uma chamada pendente para hoje."><Button icon={CalendarClock}>Ver agenda de hoje</Button></Welcome><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard label="Turmas hoje" value="3" detail="8º A, 8º B e 9º A" icon={UsersRound} tone="info" /><StatCard label="Aulas hoje" value="4" detail="Próxima às 10:20" icon={School} tone="neutral" /><StatCard label="Para corrigir" value="18" detail="2 atividades" icon={BookCheck} tone="warning" /><StatCard label="Avaliações" value="4" detail="Programadas no mês" icon={ClipboardCheck} tone="success" /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Suas turmas" action={<Link href="/professor/turmas" className="text-xs font-semibold text-blue-700">Ver todas</Link>} /><div className="grid gap-3 md:grid-cols-3">{classes.map((item) => <Link href={`/professor/turmas/${item.name.replace("º ", "-").toLowerCase()}`} key={item.name} className="group rounded-lg border border-slate-200 p-4 hover:border-blue-200 hover:bg-blue-50/30"><div className="flex items-center justify-between"><span className="text-lg font-bold text-slate-900">{item.name}</span><ArrowRight className="h-4 w-4 text-slate-300 group-hover:text-blue-600" /></div><p className="mt-1 text-xs text-slate-500">{item.subject} · {item.room}</p><div className="mt-5 flex items-center justify-between text-[11px]"><span>{item.students} alunos</span><StatusBadge tone={item.attendance >= 90 ? "success" : "warning"}>{item.attendance}% frequência</StatusBadge></div></Link>)}</div></section><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Agenda de hoje" description="Quinta-feira, 24 de setembro" /><div className="space-y-2">{[["08:00", "8º A", "Equações do 2º grau"], ["10:20", "8º B", "Revisão bimestral"], ["11:10", "9º A", "Funções quadráticas"]].map((a, i) => <div key={a[0]} className="flex gap-3 rounded-md border border-slate-100 p-3"><span className="text-xs font-bold text-blue-700">{a[0]}</span><div><p className="text-xs font-semibold">{a[1]} · Matemática</p><p className="mt-1 text-[11px] text-slate-500">{a[2]}</p></div>{i === 0 && <span className="ml-auto h-fit"><StatusBadge tone="warning">Chamada</StatusBadge></span>}</div>)}</div></section></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><Link href="/professor/chamada" className="card flex items-center gap-3 p-4 hover:border-blue-200"><div className="grid h-10 w-10 place-items-center rounded-md bg-blue-50"><UserCheck className="h-5 w-5 text-blue-700" /></div><div><p className="text-xs font-bold">Fazer chamada</p><p className="mt-1 text-[11px] text-slate-500">Registre em poucos cliques</p></div></Link><Link href="/professor/notas" className="card flex items-center gap-3 p-4 hover:border-blue-200"><div className="grid h-10 w-10 place-items-center rounded-md bg-emerald-50"><BookCheck className="h-5 w-5 text-emerald-700" /></div><div><p className="text-xs font-bold">Lançar notas</p><p className="mt-1 text-[11px] text-slate-500">Avaliações em aberto</p></div></Link><Link href="/professor/planejamento" className="card flex items-center gap-3 p-4 hover:border-blue-200"><div className="grid h-10 w-10 place-items-center rounded-md bg-amber-50"><CalendarClock className="h-5 w-5 text-amber-700" /></div><div><p className="text-xs font-bold">Planejar aula</p><p className="mt-1 text-[11px] text-slate-500">Organize a próxima semana</p></div></Link></div>
  </div>;
}

function CoordinatorDashboard() {
  const attention = students.filter((s) => s.average < 6 || s.attendance < 80 || s.occurrences >= 3).slice(0, 5);
  return <div className="page-enter"><PageHeader eyebrow="Coordenação pedagógica" title="Acompanhamento da escola" description="Indicadores para apoiar alunos, turmas e professores com agilidade." action={<Button icon={MessageSquareText}>Novo aviso</Button>} /><div className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6"><StatCard label="Alunos" value="748" detail="12 novas matrículas" icon={GraduationCap} /><StatCard label="Turmas" value="24" detail="7 séries" icon={UsersRound} tone="neutral" /><StatCard label="Professores" value="41" detail="5 áreas" icon={School} tone="neutral" /><StatCard label="Frequência média" value="93%" detail="+1,2% este mês" icon={UserCheck} tone="success" /><StatCard label="Em atenção" value="18" detail="2 casos críticos" icon={AlertTriangle} tone="warning" /><StatCard label="Registros abertos" value="6" detail="3 aguardam retorno" icon={HeartHandshake} tone="danger" /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.3fr_.7fr]"><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Alunos que precisam de acompanhamento" description="Identificados pelos critérios pedagógicos da escola" action={<Link href="/coordenacao/acompanhamento" className="text-xs font-semibold text-blue-700">Ver central</Link>} /><div className="table-wrap"><table className="data-table"><thead><tr><th>Aluno</th><th>Turma</th><th>Média</th><th>Frequência</th><th>Motivo</th><th>Situação</th></tr></thead><tbody>{attention.map((student) => <tr key={student.id}><td><Link href={`/coordenacao/alunos/${student.id}`} className="font-semibold text-slate-800 hover:text-blue-700">{student.name}</Link></td><td>{student.className}</td><td>{student.average.toFixed(1).replace(".", ",")}</td><td>{student.attendance}%</td><td>{student.average < 6 ? "Média" : student.attendance < 80 ? "Frequência" : "Registros"}</td><td><StatusBadge tone={student.average < 5.5 || student.attendance < 75 ? "danger" : "warning"}>{student.average < 5.5 || student.attendance < 75 ? "Prioritário" : "Atenção"}</StatusBadge></td></tr>)}</tbody></table></div></section><section className="space-y-4"><div className="card soft-shadow p-4 md:p-5"><SectionHeader title="Frequência da escola" description="Últimos quatro bimestres" /><PerformanceChart mode="line" /></div><Insight tone="info" icon={Activity} title="Sinal positivo" text="A frequência média subiu 1,2% nas últimas quatro semanas." /></section></div>
  </div>;
}

function DirectorDashboard() {
  return <div className="page-enter"><PageHeader eyebrow="Direção geral" title="Visão Geral da Escola" description="Colégio Modelo Horizonte · Ano letivo 2026" action={<Button icon={CalendarDays} variant="secondary">Este ano</Button>} /><div className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6"><StatCard label="Total de alunos" value="748" detail="+3,1% vs. 2025" icon={GraduationCap} trend="+22" /><StatCard label="Professores" value="41" detail="5 áreas de ensino" icon={School} tone="neutral" /><StatCard label="Turmas" value="24" detail="7 séries" icon={UsersRound} tone="neutral" /><StatCard label="Frequência média" value="93%" detail="Meta: 90%" icon={UserCheck} tone="success" /><StatCard label="Média acadêmica" value="7,8" detail="+0,4 no ano" icon={TrendingUp} tone="success" /><StatCard label="Ocorrências no mês" value="8" detail="-22% vs. agosto" icon={HeartHandshake} tone="warning" /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Evolução da frequência" description="Média mensal de todas as turmas" action={<StatusBadge tone="success">Meta superada</StatusBadge>} /><SchoolTrendChart /></section><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Distribuição de alunos" description="Por etapa de ensino" /><DistributionChart /><div className="mt-1 flex flex-wrap justify-center gap-x-4 gap-y-2">{[["6º ano", "#1e4ed8"], ["7º ano", "#3b82f6"], ["8º ano", "#148766"], ["9º ano", "#d49a24"], ["Ensino Médio", "#7c3aed"]].map(([l, c]) => <span key={l} className="flex items-center gap-1.5 text-[10px] text-slate-500"><i className="h-2 w-2 rounded-sm" style={{ background: c }} />{l}</span>)}</div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><section className="card soft-shadow p-4 md:p-5"><SectionHeader title="Panorama das turmas" action={<Link href="/direcao/turmas" className="text-xs font-semibold text-blue-700">Analisar turmas</Link>} /><div className="table-wrap"><table className="data-table"><thead><tr><th>Turma</th><th>Alunos</th><th>Média</th><th>Frequência</th><th>Registros</th><th>Situação</th></tr></thead><tbody>{classes.map((item, index) => <tr key={item.name}><td className="font-semibold">{item.name}</td><td>{item.students}</td><td>{item.average.toFixed(1).replace(".", ",")}</td><td>{item.attendance}%</td><td>{[1, 4, 0][index]}</td><td><StatusBadge tone={item.average >= 7.5 ? "success" : "warning"}>{item.average >= 7.5 ? "Adequada" : "Acompanhar"}</StatusBadge></td></tr>)}</tbody></table></div></section><section className="space-y-3"><Insight tone="success" icon={CheckCircle2} title="Frequência em alta" text="18 das 24 turmas estão acima da meta estabelecida." /><Insight tone="warning" icon={AlertTriangle} title="Ponto de atenção" text="O 8º B apresentou queda de 0,6 ponto na média deste período." /><Insight tone="info" icon={Sparkles} title="Desempenho" text="Ciências teve a maior evolução entre as áreas neste bimestre." /></section></div>
  </div>;
}
